[gov_officials]
delegate = 'Griffindor'
pm = 'ProfessorHenn'
mofa = 'HumanSanity'
mod = 'Shibuya-Kanon'
morp = 'Maverick'
mooe = 'Legend'
moi = 'Pronoun'
owl_sec = 'Em'
hc_chief_justice = 'Kringle'
hc_justices = ['Kringle', 'Belschaft', 'Griffindor', 'Pronoun']
coa = 'Cryo'
crs = ['Amerion', 'Anjo', 'Farengeto', 'Glen-Rhodes', 'Kringle', 'Tsunamy',  'Penguin', 'Em']
spcg = ['Amerion', 'Aidenfieeld', 'Anjo', 'Farengeto', 'Griffindor', 'Land Without Shrimp', 'Tsunamy', 'Penguin']
legcomm = ['Anjo', 'HumanSanity', 'Purple Hyacinth']
general_corps = ['HumanSanity', 'Pronoun']
cabinet_advisors = []

[personnel_info]
[personnel_info.Aidenfieeld]
nation = 'Aidenfieeld'
discord_handle = 'Aidenfieeld#7386'
[personnel_info.'Amerion']
nation = 'Amerion'
discord_handle = 'amerion'
[personnel_info.'Anjo']
nation = 'Tepertopia'
discord_handle = 'anjo0803'
[personnel_info.'Belschaft']
nation = 'Belschaft'
discord_handle = 'belschaft'
[personnel_info.'Cryo']
nation = 'The Haughtherlands'
discord_handle = 'cryophoric'
[personnel_info.'Em']
nation = 'Qvait'
discord_handle = 'gamingberserkr'
[personnel_info.'Farengeto']
nation = 'Farengeto'
discord_handle = 'The Other Farengeto#7220'
[personnel_info.'Glen-Rhodes']
nation = 'Sandaoguo'
discord_handle = 'hierocles'
[personnel_info.'Griffindor']
nation = 'Ebonhand'
discord_handle = '.griffindor'
[personnel_info.'HumanSanity']
nation = 'HumanSanity'
discord_handle = 'humansanity'
[personnel_info.'Kringle']
nation = 'Kringalia'
discord_handle = 'kris_kringle'
[personnel_info.'Land Without Shrimp']
nation = 'Land Without Shrimp'
discord_handle = 'sonofthunder7'
[personnel_info.'Legend']
nation = 'New American Dictatorship'
discord_handle = 'aquariusblue899'
[personnel_info.'Maverick']
nation = 'Maverick'
discord_handle = 'based.maverick'
[personnel_info.'Penguin']
nation = 'PenguinPies'
discord_handle = 'ladypenguin55'
[personnel_info.'ProfessorHenn']
nation = 'Sporaltryus'
discord_handle = 'professorhenn'
[personnel_info.'Pronoun']
nation = 'Esfalsa'
discord_handle = 'pronoun'
[personnel_info.'Purple Hyacinth']
nation = 'Purple Hyacinth'
discord_handle = 'flowerpetal'
[personnel_info.'Shibuya-Kanon']
nation = 'Kinako Sakurakoji'
discord_handle = 'megumi_fujishima'
[personnel_info.'Tsunamy']
nation = 'Tsunamy'
discord_handle = 'tsu_namy'
