[gov_officials]
delegate = 'Anjo'
pm = 'ProfessorHenn'
mofa = 'HumanSanity'
mod = 'Concrete Slab'
moc = 'Maluhia'
moe = 'Griffindor'
owl_sec = 'Concrete Slab'
hc_chief_justice = 'Kringle'
hc_justices = ['Kringle', 'Belschaft', 'Griffindor']
coa = 'Cryo'
local_council = ['Evinea', 'Petea', 'TescoPepsi']
crs = ['Amerion', 'Farengeto', 'Glen-Rhodes', 'Kringle', 'Tsunamy',  'Penguin', 'Jay']
spcg = ['Amerion', 'Aidenfieeld', 'Anjo', 'Farengeto', 'Griffindor', 'Land Without Shrimp', 'Poppy', 'Tsunamy', 'Penguin']
legcomm = ['Anjo', 'HumanSanity']
general_corps = ['HumanSanity']
cabinet_advisors = []

[personnel_info]
[personnel_info.Aidenfieeld]
nation = 'Aidenfieeld'
discord_handle = 'Aidenfieeld#7386'
[personnel_info.'Amerion']
nation = 'Amerion'
discord_handle = 'Amerion#9702'
[personnel_info.'Anjo']
nation = 'Tepertopia'
discord_handle = 'anjo#3888'
[personnel_info.'Belschaft']
nation = 'Belschaft'
discord_handle = 'Belschaft#0942'
[personnel_info.'Canadian Dominion']
nation = 'Canadian Dominion'
discord_handle = 'NK-Pop#3817'
[personnel_info.'Concrete Slab']
nation = 'Concrete Slab'
discord_handle = 'Concrete Slab#8764'
[personnel_info.'Cryo']
nation = 'The Haughtherlands'
discord_handle = 'Cryophoric#6034'
[personnel_info.'Evinea']
nation = 'Evinea'
discord_handle = 'mn04#0192'
[personnel_info.'Farengeto']
nation = 'Farengeto'
discord_handle = 'The Other Farengeto#7220'
[personnel_info.'ProfessorHenn']
nation = 'Sporaltryus'
discord_handle = 'ProfessorHenn#7751'
[personnel_info.'Glen-Rhodes']
nation = 'Sandaoguo'
discord_handle = 'hierocles#3041'
[personnel_info.'Griffindor']
nation = 'Ebonhand'
discord_handle = 'Griffindor#9422'
[personnel_info.'HumanSanity']
nation = 'HumanSanity'
discord_handle = 'HumanSanity#9270'
[personnel_info.'Jay']
nation = 'Qvait'
discord_handle = 'JayCoop#5045'
[personnel_info.'Kringle']
nation = 'Kringalia'
discord_handle = 'Kringle#7460'
[personnel_info.'Land Without Shrimp']
nation = 'Land Without Shrimp'
discord_handle = 'James LWS Encaitar#6762'
[personnel_info.'Maluhia']
nation = 'Lile Ulie Islands'
discord_handle = 'maluhia#2206'
[personnel_info.'Penguin']
nation = 'PenguinPies'
discord_handle = 'Penguin#0738'
[personnel_info.'Poppy']
nation = '073 039 109 032 080 111 112 112 121'
discord_handle = 'Poppy#5885'
[personnel_info.'Petea']
nation = 'Petea'
discord_handle = 'king.fenik#6963'
[personnel_info.'Tsunamy']
nation = 'Tsunamy'
discord_handle = 'tsu#6405'
[personnel_info.'TescoPepsi']
nation = 'TescoPepsi'
discord_handle = 'parisdcmol#9055'
