[gov_officials]
delegate = 'Anjo'
pm = 'Jay'
mofa = 'HumanSanity'
mod = 'Pronoun'
moc = 'LUI'
moe = 'Griffindor'
owl_sec = 'Anjo'
hc_chief_justice = 'Kringle'
hc_justices = ['Kringle', 'Belschaft', 'Griffindor', 'Roavin']
coa = 'Cryo'
local_council = ['Curlyhoward', 'Trivalve', 'The free romanians']
crs = ['Amerion', 'Farengeto', 'Glen-Rhodes', 'Kringle', 'Tsunamy',  'Penguin', 'Jay']
spcg = ['Amerion', 'Aidenfieeld','Anjo','Concrete Slab', 'Farengeto', 'Griffindor', 'Land Without Shrimp', 'Poppy', 'Tin', 'Tsunamy', 'Penguin']
legcomm = ['Penguin', 'Anjo', 'HumanSanity']
general_corps = ['HumanSanity']
cabinet_advisors = []

[personnel_info]
[personnel_info.Aidenfieeld]
nation = 'Aidenfieeld'
discord_handle = 'Aidenfieeld#7386'
[personnel_info.'Amerion']
nation = 'Amerion'
discord_handle = 'Amerion#9702'
[personnel_info.'Anjo']
nation = 'Tepertopia'
discord_handle = 'anjo#3888'
[personnel_info.'Belschaft']
nation = 'Belschaft'
discord_handle = 'Belschaft#0942'
[personnel_info.'BlockBuster']
nation = 'Great Lothian'
discord_handle = 'BlockBuster2K43#6162'
[personnel_info.'Canadian Dominion']
nation = 'Canadian Dominion'
discord_handle = 'NK-Pop#3817'
[personnel_info.'Concrete Slab']
nation = 'Concrete Slab'
discord_handle = 'Concrete Slab#8764'
[personnel_info.'Cryo']
nation = 'The Haughtherlands'
discord_handle = 'Cryophoric#6034'
[personnel_info.'Curlyhoward']
nation = 'Curlyhoward'
discord_handle = 'mightyjoeyoung1#6247'
[personnel_info.'Drystar']
nation = 'Drystar'
discord_handle = 'Drystar#5371'
[personnel_info.'Eshia']
nation = 'Klysevia'
discord_handle = 'William!#1136'
[personnel_info.'Evinea']
nation = 'Evinea'
discord_handle = 'mn04#0192'
[personnel_info.'Farengeto']
nation = 'Farengeto'
discord_handle = 'The Other Farengeto#7220'
[personnel_info.'Floptop']
nation = 'Lebatrip'
discord_handle = 'Floptop F. Kennedy#3443'
[personnel_info.'Glen-Rhodes']
nation = 'Sandaoguo'
discord_handle = 'hierocles#3041'
[personnel_info.'Griffindor']
nation = 'Ebonhand'
discord_handle = 'Griffindor#9422'
[personnel_info.'HumanSanity']
nation = 'HumanSanity'
discord_handle = 'HumanSanity#9270'
[personnel_info.'Jay']
nation = 'Qvait'
discord_handle = 'JayCoop#5045'
[personnel_info.'Kringle']
nation = 'Kringalia'
discord_handle = 'Kringle#7460'
[personnel_info.'Land Without Shrimp']
nation = 'Land Without Shrimp'
discord_handle = 'James LWS Encaitar#6762'
[personnel_info.'Moon']
nation = 'Emodea'
discord_handle = 'Moon_#5541'
[personnel_info.'Murelia']
nation = 'Murelia'
discord_handle = 'Murelia#9532'
[personnel_info.'Nakari']
nation = 'Nakarisaune'
discord_handle = 'Nakari#3538'
[personnel_info.'Penguin']
nation = 'PenguinPies'
discord_handle = 'Penguin#0738'
[personnel_info.'Poppy']
nation = '073 039 109 032 080 111 112 112 121'
discord_handle = 'Poppy#5885'
[personnel_info.'Purple Hyacinth']
nation = 'Purple Hyacinth'
discord_handle = 'flowerpetal#4093'
[personnel_info.'Pronoun']
nation = 'Esfalsa'
discord_handle = 'Pronoun#2968'
[personnel_info.'Roavin']
nation = 'Roavin'
discord_handle = 'Roavin#5410'
[personnel_info.'LUI']
nation = 'Lile Ulie Islands'
discord_handle = 'the lile ulie islands#2206'
[personnel_info.'The free romanians']
nation = 'The free romanians'
[personnel_info.'Tin']
nation = 'Holy Free'
discord_handle = 'Tin#6571'
[personnel_info.'Tsunamy']
nation = 'Tsunamy'
discord_handle = 'tsu#6405'
[personnel_info.'Trivalve']
nation = 'Trivalve'
[personnel_info.'USoVietnam']
nation = 'United States of Vietnam'
discord_handle = 'watari#5292'
[personnel_info.'Wizard Ferret']
nation = 'Wizard Ferret'
discord_handle = 'wizardferret#3359'
