[gov_officials]
delegate = 'Griffindor'
pm = 'Penguin'
mofa = 'ProfessorHenn'
mod = 'Vrigny'
moc = 'Silva'
owl_director = 'lordnwahs'
hc_chief_justice = 'Kringle'
hc_justices = ['Kringle', 'Belschaft', 'Griffindor', 'Pronoun']
coa = 'BlockBuster2K43'
crs = [
    'Amerion',
    'Anjo',
    'HumanSanity',
    'Glen-Rhodes',
    'Kringle',
    'Tsunamy',
    'Em',
]
spcg = [
    'Aidenfieeld',
    'Amerion',
    'Anjo',
    'Griffindor',
    'Land Without Shrimp',
    'ProfessorHenn',
    'Tsunamy',
]
citcomm = ['Anjo', 'Pronoun']
admiralty = ['HumanSanity', 'Pronoun', 'Vrigny']

[people_info]
[people_info.Aidenfieeld]
nation = 'Aidenfieeld'
discord_handle = 'Aidenfieeld#7386'
[people_info.'Amerion']
nation = 'Amerion'
discord_handle = 'amerion'
[people_info.'Anjo']
nation = 'Tepertopia'
discord_handle = 'anjo0803'
[people_info.'Belschaft']
nation = 'Belschaft'
discord_handle = 'belschaft'
[people_info.'BlockBuster2K43']
nation = 'Great Lothian'
discord_handle = 'blockbuster2k43'
[people_info.'Em']
nation = 'Qvait'
discord_handle = 'gamingberserkr'
[people_info.'Glen-Rhodes']
nation = 'Sandaoguo'
discord_handle = 'hierocles'
[people_info.'Griffindor']
nation = 'Ebonhand'
discord_handle = '.griffindor'
[people_info.'HumanSanity']
nation = 'HumanSanity'
discord_handle = 'humansanity'
[people_info.'Kringle']
nation = 'Kringalia'
discord_handle = 'kris_kringle'
[people_info.'Land Without Shrimp']
nation = 'Land Without Shrimp'
discord_handle = 'sonofthunder7'
[people_info.'lordnwahs']
nation = 'Differences-In-Differences'
discord_handle = 'lordnwahs'
[people_info.'Penguin']
nation = 'PenguinPies'
discord_handle = 'ladypenguin55'
[people_info.'ProfessorHenn']
nation = 'Sporaltryus'
discord_handle = 'professorhenn'
[people_info.'Pronoun']
nation = 'Esfalsa'
discord_handle = 'pronoun'
[people_info.'Silva']
nation = 'Virifortis'
discord_handle = 'silvae_'
[people_info.'Tsunamy']
nation = 'Tsunamy'
discord_handle = 'tsu_namy'
[people_info.'Vrigny']
nation = 'Vrigny'
discord_handle = 'vrigny'
