[gov_officials]
delegate = 'Amerion'
pm = 'HumanSanity'
mofa = 'Roavin'
mod = 'Moon'
moc = 'Waffle'
mom = 'Floptop'
moe = 'Purple Hyacinth'
owl_sec = 'Jay'
hc_chief_justice = 'Kringle'
hc_justices = ['Kringle', 'Belschaft', 'Griffindor', 'Roavin']
coa = 'Anjo'
local_council = ['Drystar', 'Canadian Dominion', 'Apatosaurus']
crs = ['Glen-Rhodes', 'Farengeto', 'Kringle', 'Tsunamy', 'Amerion', 'Penguin', 'Jay']
spcg = ['tepertopia','auphelia','concrete slab','073 039 109 032 080 111 112 112 121', 'aidenfieeld', 'beepee', 'ebonhand', 'purple hyacinth', 'land without shrimp', 'holy free', 'amerion', 'penguinpies', 'tsunamy']
legcomm = ['Roavin', 'W&S', 'Nakari', 'Penguin', 'Anjo']
general_corps = ['Roavin', 'Nakari', 'W&S']
cabinet_advisors = []

[personnel_info]
[personnel_info.Aidenfieeld]
nation = 'Aidenfieeld'
discord_handle = 'Aidenfieeld#7386'
[personnel_info.'Amerion']
nation = 'Amerion'
discord_handle = 'Amerion#9702'
[personnel_info.'Anjo']
nation = 'Tepertopia'
discord_handle = 'anjo#3888'
[personnel_info.'Apatosaurus']
nation = 'Apatosaurus'
discord_handle = 'Apatosaurus#8045'
[personnel_info.'Auphelia']
nation = 'Auphelia'
discord_handle = 'Quarrelsome Queen#0882'
[personnel_info.'Beepee']
nation = 'Beepee'
discord_handle = 'Beepee#5411'
[personnel_info.'Belschaft']
nation = 'Belschaft'
discord_handle = 'Belschaft#0942'
[personnel_info.'Canadian Dominion']
nation = 'Canadian Dominion'
discord_handle = 'NK-Pop#3817'
[personnel_info.'Concrete Slab']
nation = 'Concrete Slab'
discord_handle = 'Concrete Slab#8764'
[personnel_info.'Drystar']
nation = 'Drystar'
discord_handle = 'Drystar#5371'
[personnel_info.'Farengeto']
nation = 'Farengeto'
discord_handle = 'The Other Farengeto#7220'
[personnel_info.'Floptop']
nation = 'Lebatrip'
discord_handle = 'Floptop F. Kennedy#3443'
[personnel_info.'Glen-Rhodes']
nation = 'Sandaoguo'
discord_handle = 'hierocles#3041'
[personnel_info.'Griffindor']
nation = 'Ebonhand'
discord_handle = 'Griffindor#9422'
[personnel_info.'HumanSanity']
nation = 'HumanSanity'
discord_handle = 'HumanSanity#9270'
[personnel_info.'Jay']
nation = 'Qvait'
discord_handle = 'JayCoop#5045'
[personnel_info.'Kringle']
nation = 'Kringalia'
discord_handle = 'Kringle#7460'
[personnel_info.'Land Without Shrimp']
nation = 'Land Without Shrimp'
discord_handle = 'James LWS Encaitar#6762'
[personnel_info.'Moon']
nation = 'Emodea'
discord_handle = 'Moon_#5541'
[personnel_info.'Nakari']
nation = 'Nakarisaune'
discord_handle = 'Nakari#3538'
[personnel_info.'Penguin']
nation = 'PenguinPies'
discord_handle = 'Penguin#0738'
[personnel_info.'Poppy']
nation = '073 039 109 032 080 111 112 112 121'
discord_handle = 'Poppy#5885'
[personnel_info.'Purple Hyacinth']
nation = 'Purple Hyacinth'
discord_handle = 'flowerpetal#4093'
[personnel_info.'Roavin']
nation = 'Roavin'
discord_handle = 'Roavin#5410'
[personnel_info.'Tin']
nation = 'Holy Free'
discord_handle = 'Tin#6571'
[personnel_info.'Tsunamy']
nation = 'Tsunamy'
discord_handle = 'tsu#6405'
[personnel_info.'W&S']
nation = 'Witchcraft and Sorcery'
discord_handle = 'WynkenBlynken#1150'
[personnel_info.'Waffle']
nation = 'Doge Land'
discord_handle = 'im_a_waffle1#9951'
