[gov_officials]
delegate = 'Griffindor'
pm = 'ProfessorHenn'
mofa = 'Concrete Slab'
mod = 'Banexet'
morp = 'Of_the_Ages'
moc = 'Legend'
moi = 'USoVietnam'
owl_sec = 'Em'
hc_chief_justice = 'Kringle'
hc_justices = ['Kringle', 'Belschaft', 'Griffindor', 'Pronoun']
coa = 'BlockBuster2K43'
crs = [
    'Amerion',
    'Anjo',
    'Farengeto',
    'Glen-Rhodes',
    'Kringle',
    'Tsunamy',
    'Penguin',
    'Em',
]
spcg = [
    'Amerion',
    'Aidenfieeld',
    'Anjo',
    'Farengeto',
    'Griffindor',
    'Land Without Shrimp',
    'Tsunamy',
    'Penguin',
    'ProfessorHenn',
]
legcomm = ['Anjo', 'Pronoun', 'Purple Hyacinth']
general_corps = ['HumanSanity', 'Pronoun']
cabinet_advisors = []

[people_info]
[people_info.Aidenfieeld]
nation = 'Aidenfieeld'
discord_handle = 'Aidenfieeld#7386'
[people_info.'Amerion']
nation = 'Amerion'
discord_handle = 'amerion'
[people_info.'Anjo']
nation = 'Tepertopia'
discord_handle = 'anjo0803'
[people_info.'Belschaft']
nation = 'Belschaft'
discord_handle = 'belschaft'
[people_info.'Banexet']
nation = 'Drew Durrnil'
discord_handle = 'banexet'
[people_info.'BlockBuster2K43']
nation = 'Great Lothian'
discord_handle = 'blockbuster2k43'
[people_info.'Concrete Slab']
nation = 'Concrete Slab'
discord_handle = 'concrete.slab'
[people_info.'Em']
nation = 'Qvait'
discord_handle = 'gamingberserkr'
[people_info.'Farengeto']
nation = 'Farengeto'
discord_handle = 'The Other Farengeto#7220'
[people_info.'Glen-Rhodes']
nation = 'Sandaoguo'
discord_handle = 'hierocles'
[people_info.'Griffindor']
nation = 'Ebonhand'
discord_handle = '.griffindor'
[people_info.'HumanSanity']
nation = 'HumanSanity'
discord_handle = 'humansanity'
[people_info.'Kringle']
nation = 'Kringalia'
discord_handle = 'kris_kringle'
[people_info.'Land Without Shrimp']
nation = 'Land Without Shrimp'
discord_handle = 'sonofthunder7'
[people_info.'Legend']
nation = 'New American Dictatorship'
discord_handle = 'aquariusblue899'
[people_info.'Of_the_Ages']
nation = 'The Age of Utopia'
discord_handle = 'the_age_of_utopia'
[people_info.'Penguin']
nation = 'PenguinPies'
discord_handle = 'ladypenguin55'
[people_info.'ProfessorHenn']
nation = 'Sporaltryus'
discord_handle = 'professorhenn'
[people_info.'Pronoun']
nation = 'Esfalsa'
discord_handle = 'pronoun'
[people_info.'Purple Hyacinth']
nation = 'Purple Hyacinth'
discord_handle = 'flowerpetal'
[people_info.'Shibuya-Kanon']
nation = 'Kinako Sakurakoji'
discord_handle = 'megumi_fujishima'
[people_info.'Tsunamy']
nation = 'Tsunamy'
discord_handle = 'tsu_namy'
[people_info.'USoVietnam']
nation = 'United States of Vietnam'
discord_handle = 'watari5292'
