[p]
template = '[font=Avenir, Segoe UI, sans-serif][size=120]%(value)s[/size][/font]'

[title]
template = '[center][font=Avenir, Segoe UI, sans-serif][size=250][color=#109aed][b]%(value)s[/b][/color][/size][/font][/center]'

[subtitle]
template = '[center][font=Avenir, Segoe UI, sans-serif][size=160][color=#109aed][b]%(value)s[/b][/color][/size][/font][/center]'

[h1]
template = '[font=Avenir, Segoe UI, sans-serif][size=250][color=#109aed][b]%(value)s[/b][/color][/size][/font]'

[h2]
template = '[font=Avenir, Segoe UI, sans-serif][size=170][color=#109aed][b]%(value)s[/b][/color][/size][/font]'

[h3]
template = '[font=Avenir, Segoe UI, sans-serif][size=140][color=#109aed][b]%(value)s[/b][/color][/size][/font]'

[h4]
template = '[font=Avenir, Segoe UI, sans-serif][size=130][color=#109aed][b]%(value)s[/b][/color][/size][/font]'

[em]
template = '[color=#109aed][b]%(value)s[/b][/color]'

[danger]
template = '[color=#ff0000][b]%(value)s[/b][/color]'

[raw]
template = '%(value)s'

['*']
template = '[*][font=Avenir, Segoe UI, sans-serif][size=120]%(value)s[/size][/font]'
render_embedded = true
newline_closes = true
same_tag_closes = true

['*_r']
template = '[*]%(value)s'
render_embedded = true
newline_closes = true
same_tag_closes = true