[gov_officials]
delegate = 'Amerion'
pm = 'Witchcraft and Sorcery'
mofa = 'Qvait'
mod = 'HumanSanity'
moc = 'Holy Free'
mom = 'Moonfungus'
moe = 'Lucabaduka'
owl_sec = 'Tepertopia'
hc_chief_justice = 'Kringalia'
hc_justices = ['Kringalia', 'Belschaft', 'Ebonhand', 'Roavin']
coa = 'Purple Hyacinth'
election_commissioner = 'Erinor'
local_council = ['PenguinPies', 'Erinor', 'Murelia']
crs = ['Sandaoguo', 'Farengeto', 'Kringalia', 'Erinor', 'Tsunamy', 'Aumeltopia', 'Amerion', 'Qvait', 'PenguinPies']
legcomm = ['Roavin', 'Witchcraft and Sorcery', 'Nakarisaune']
general_corps = ['Roavin', 'Nakarisaune']
cabinet_advisors = ['Nakarisaune']

[personnel_info]
[personnel_info.Amerion]
nation = 'Amerion'
discord_handle = 'Amerion#9702'
[personnel_info.'W&S']
nation = 'Witchcraft and Sorcery'
discord_handle = 'WynkenBlynken#1150'
[personnel_info.'Qvait']
nation = 'Qvait'
discord_handle = 'JayCoop#5045'
[personnel_info.'HumanSanity']
nation = 'HumanSanity'
discord_handle = 'HumanSanity#9270'
[personnel_info.'Tin']
nation = 'Holy Free'
discord_handle = 'Tin#6571'
[personnel_info.'Moonfungus']
nation = 'Emodea'
discord_handle = 'Moon_#5541'
[personnel_info.'Luca']
nation = 'Luca'
discord_handle = 'Luca#0004'
[personnel_info.'Anjo']
nation = 'Tepertopia'
discord_handle = 'anjo#3888'
[personnel_info.'Purple Hyacinth']
nation = 'Purple Hyacinth'
discord_handle = 'flowerpetal#4093'
[personnel_info.'Kringle']
nation = 'Kringalia'
discord_handle = 'Kringle#7460'
[personnel_info.'Roavin']
nation = 'Roavin'
discord_handle = 'Roavin#5410'
[personnel_info.'Belschaft']
nation = 'Belschaft'
discord_handle = 'Belschaft#0942'
[personnel_info.'Griffindor']
nation = 'Ebonhand'
discord_handle = 'Griffindor#9422'
[personnel_info.'Seraph']
nation = 'Erinor'
discord_handle = 'Seraph#4235'
[personnel_info.'Penguin']
nation = 'PenguinPies'
discord_handle = 'Penguin#0738'
[personnel_info.'Murelia']
nation = 'Witchcraft and Sorcery'
discord_handle = 'WynkenBlynken#1150'
[personnel_info.'Tsunamy']
nation = 'Tsunamy'
discord_handle = 'tsu#6405'
[personnel_info.'Glen-Rhodes']
nation = 'Sandaoguo'
discord_handle = 'hierocles#3041'
[personnel_info.'Somyrion']
nation = 'Aumeltopia'
discord_handle = 'Somyrion#8047'
[personnel_info.'Nakari']
nation = 'Nakarisaune'
discord_handle = 'Nakari#3538'
[personnel_info.'Farengeto']
nation = 'Farengeto'
discord_handle = 'The Other Farengeto#7220'
