[p]
format_string = '[font=Avenir, Segoe UI, sans-serif][size=120]%(value)s[/size][/font]'

[title]
format_string = '[center][font=Avenir, Segoe UI, sans-serif][size=250][color=#109aed][b]%(value)s[/b][/color][/size][/font][/center]'

[subtitle]
format_string = '[center][font=Avenir, Segoe UI, sans-serif][size=160][color=#109aed][b]%(value)s[/b][/color][/size][/font][/center]'

[h1]
format_string = '[font=Avenir, Segoe UI, sans-serif][size=200][color=#109aed][b]%(value)s[/b][/color][/size][/font]'

[h2]
format_string = '[font=Avenir, Segoe UI, sans-serif][size=170][color=#109aed][b]%(value)s[/b][/color][/size][/font]'

[h3]
format_string = '[font=Avenir, Segoe UI, sans-serif][size=140][color=#109aed][b]%(value)s[/b][/color][/size][/font]'

[h4]
format_string = '[font=Avenir, Segoe UI, sans-serif][size=130][color=#109aed][b]%(value)s[/b][/color][/size][/font]'

[em]
format_string = '[color=#109aed][b]%(value)s[/b][/color]'

[danger]
format_string = '[color=#ff0000][b]%(value)s[/b][/color]'

[url_content]
format_string = '[color=#ff9900]%(value)s[/color]'

[td_content]
format_string = '[font=Avenir, Segoe UI, sans-serif][size=120]%(value)s[/size][/font]'

[th_content]
format_string = '[font=Avenir, Segoe UI, sans-serif][size=130][color=#109aed][b]%(value)s[/b][/color][/size][/font]'

[tt_content]
format_string = '[background-block=#1089e6][hr][center][font=Avenir, Segoe UI, sans-serif][size=140][color=#ffffff][b]%(value)s[/b][/color][/size][/font][/center][hr][/background-block]'

['*_content']
format_string = '[font=Avenir, Segoe UI, sans-serif][size=120]%(value)s[/size][/font]'
render_embedded = true
newline_closes = true
same_tag_closes = true

[raw]
format_string = '%(value)s'
render_embedded = false

[pre]
format_string = '[pre]%(value)s[/pre]'
render_embedded = false
