[coalition_of_the_south_pacific."design_guides/formatting_guide"]
title = "How to format dispatches with TSP Dispatch Service editing system"
category = "meta"
subcategory = "gameplay"
ns_id = "1584528"
