[coalition_of_the_south_pacific."laws/charter_of_the_south_pacific"]
title = "The Charter of the South Pacific"
category = "meta"
subcategory = "reference"
ns_id = "1569641"

[coalition_of_the_south_pacific."laws/elections_act"]
title = "The Elections Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569642"

[coalition_of_the_south_pacific."laws/legislative_procedure_act"]
title = "Legislative Procedure Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569643"

[coalition_of_the_south_pacific."laws/legislator_committee_act"]
title = "Legislator Committee Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569644"

[coalition_of_the_south_pacific."laws/proscription_act"]
title = "Proscription Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569645"

[coalition_of_the_south_pacific."laws/border_control_act"]
title = "Border Control Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569646"

[coalition_of_the_south_pacific."laws/criminal_code"]
title = "Criminal Code - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569647"

[coalition_of_the_south_pacific."laws/cultural_act"]
title = "Cultural Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569648"

[coalition_of_the_south_pacific."laws/judicial_act"]
title = "Judicial Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569649"

[coalition_of_the_south_pacific."laws/law_standards_act"]
title = "Law Standards Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569650"

[coalition_of_the_south_pacific."laws/military_code"]
title = "Military Code - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569651"

[coalition_of_the_south_pacific."laws/political_parties_act"]
title = "Political Parties Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569652"

[coalition_of_the_south_pacific."laws/regional_communications_act"]
title = "Regional Communications Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569653"

[coalition_of_the_south_pacific."laws/regional_officers_act"]
title = "Regional Officers Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569655"

[coalition_of_the_south_pacific."laws/sunshine_act"]
title = "Sunshine Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569657"

[coalition_of_the_south_pacific."laws/times_act"]
title = "Times Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569659"

[coalition_of_the_south_pacific."laws/treaties_act"]
title = "Treaties Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569660"

[coalition_of_the_south_pacific."laws/whistleblower_protection_act"]
title = "Whistleblower Protection Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1569661"

[coalition_of_the_south_pacific."laws/world_assembly_act"]
title = "World Assembly Act - TSP"
category = "meta"
subcategory = "reference"
ns_id = "1570717"
